{
 "title": "Buy/Sell Stock Analysis",
 "time": { "from": "2025-04-15T04:15:14.092Z", "to": "2025-04-15T04:32:18.712Z" },
 "panels": [
  {
   "title": "IS 6850 Final Project - Stock Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Buy Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data\")\r\n  |> range(start: -30m)  // or whatever time window you want\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"stock_events\" and\r\n    r._field == \"price\" and\r\n    r.event_type == \"buy\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"ticker\"])\r\n  |> group(columns: [\"ticker\"])"
    }
   ]
  },
  {
   "title": "Sell Events",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data\")\r\n  |> range(start: -30m)  // or whatever time window you want\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"stock_events\" and\r\n    r._field == \"price\" and\r\n    r.event_type == \"sell\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"ticker\"])\r\n  |> group(columns: [\"ticker\"])"
    }
   ]
  },
  {
   "title": "Anomalies",
   "type": "table",
   "gridPos": { "h": 10, "w": 22, "x": 1, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"anomaly_events\" and\r\n    r._field == \"price\")  // Only using one field to avoid row duplication\r\n  |> keep(columns: [\"_time\", \"ticker\", \"event_type\", \"anomaly_flag\", \"_value\"])\r\n  |> rename(columns: {_value: \"price\"})\r\n  |> group()\r\n"
    }
   ]
  }
 ]
}